# **Accediendo a `filas` y `columnas` con Pandas**

In [102]:
import pandas as pd

In [103]:
df = pd.read_csv("datos_ventas.csv", sep=";")

df.head()

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,3/06/24,1000,3,3000
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500

In [104]:
df["Matricula"].head()

0    123456111
1    123456111
2    123456333
3    123456333
4    123456333
Name: Matricula, dtype: int64

In [105]:
# Solo cuando no hay caracteres especiales o espacios en blanco. Aplicar buenas prácticas para nombrar columnas
df.Matricula.head()

0    123456111
1    123456111
2    123456333
3    123456333
4    123456333
Name: Matricula, dtype: int64

In [106]:
df.columns

Index(['CodigoTienda', 'Tienda', 'CodigoProducto', 'DescripcionProduto',
       'Matricula', 'NombreVendedor', 'FechaDeVenta', 'PrecioUnitario',
       'Cantidad', 'Valorventa'],
      dtype='str')

In [107]:
# Accediendo a varias columnas
df[['CodigoTienda', 'Tienda', 'CodigoProducto', 'DescripcionProduto']]

   CodigoTienda  Tienda  CodigoProducto       DescripcionProduto
0      TIENDA01  Matriz           10001               Smartphone
1      TIENDA01  Matriz           10001               Smartphone
2      TIENDA01  Matriz           10002                   Tablet
3      TIENDA01  Matriz           10002                   Tablet
4      TIENDA01  Matriz           10003                Televisor
5      TIENDA01  Matriz           10004                 Lavadora
6      TIENDA01  Matriz           10005                   Laptop
7      TIENDA01  Matriz           10005                   Laptop
8      TIENDA01  Matriz           10007                Mezclador
9      TIENDA01  Matriz           10008                 Cafetera
10     TIENDA01  Matriz           10010         Freidor elétrico
11     TIENDA01  Matriz           10010         Freidor elétrico
12     TIENDA01  Matriz           10011                Licuadora
13     TIENDA01  Matriz           10011                Licuadora
14     TIENDA01  Matriz           10012  Procesador de alimentos
15     TIENDA01  Matriz           10012  Procesador de alimentos
16     TIENDA01  Matriz           10013                   Estufa
17     TIENDA01  Matriz           10013                   Estufa
18     TIENDA01  Matriz           10013                   Estufa
19     TIENDA01  Matriz           10014             Refrigerador
20     TIENDA01  Matriz           10014             Refrigerador
21     TIENDA01  Matriz           10014             Refrigerador
22     TIENDA01  Matriz           10016                  Armario
23     TIENDA01  Matriz           10016                  Armario
24     TIENDA01  Matriz           10016                  Armario
25     TIENDA01  Matriz           10016                  Armario
26     TIENDA01  Matriz           10016                  Armario
27     TIENDA01  Matriz           10017                     Cama
28     TIENDA01  Matriz           10018                  Colchón
29     TIENDA01  Matriz           10018                  Colchón
30     TIENDA01  Matriz           10018                  Colchón
31     TIENDA01  Matriz           10020                Impresora
32     TIENDA01  Matriz           10020                Impresora

In [108]:
# Accediendo a varias columnas
columnas = ['CodigoTienda', 'Tienda', 'CodigoProducto', 'DescripcionProduto'] # Explicare ventaja de hacerlo así (no cambiar en todas partes)
df[columnas].head()

  CodigoTienda  Tienda  CodigoProducto DescripcionProduto
0     TIENDA01  Matriz           10001         Smartphone
1     TIENDA01  Matriz           10001         Smartphone
2     TIENDA01  Matriz           10002             Tablet
3     TIENDA01  Matriz           10002             Tablet
4     TIENDA01  Matriz           10003          Televisor

## **Métodos `iloc` y `loc`**

Son dos de los `métodos` más importantes en **Pandas** para acceder a datos dentro de un `DataFrame`. Aunque son similares, tienen diferencias clave en cómo seleccionan filas y columnas.

| Método | Tipo índice | Qué acepta | Ejemplo |
| --- | --- | --- | --- |
| `iloc[fila, columna]` | Índices enteros (posición) | enteros, listas, rangos, slices | `df.iloc[0, 1]` |
| `loc[fila, columna]` | Índices etiquetados (nombre) | etiquetas, listas de etiquetas, condiciones booleanas | `df.loc["Juan", "edad"]` |


*** El método `iloc` aparece como ***deprecated*** en la documentación de **pandas**.

In [109]:
df.head()

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,3/06/24,1000,3,3000
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500

### `iloc`

In [110]:
df.iloc[3]

CodigoTienda              TIENDA01
Tienda                      Matriz
CodigoProducto               10002
DescripcionProduto          Tablet
Matricula                123456333
NombreVendedor        Jorge Mateus
FechaDeVenta               3/06/24
PrecioUnitario                1000
Cantidad                         3
Valorventa                    3000
Name: 3, dtype: object

In [111]:
# slicing de filas no es inclusivo el lim superior
df.iloc[0:2]

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000

In [112]:
df.iloc[25:]

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
25,TIENDA01,Matriz,10016,Armario,123456111,Jose Martinez,11/10/24,1500,1,1500
26,TIENDA01,Matriz,10016,Armario,123456333,Jorge Mateus,24/01/24,1500,1,1500
27,TIENDA01,Matriz,10017,Cama,123456333,Jorge Mateus,16/09/24,2800,1,2800
28,TIENDA01,Matriz,10018,Colchón,123456111,Jose Martinez,22/12/24,310,2,620
29,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,13/04/24,310,3,930
30,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,10/09/24,310,3,930
31,TIENDA01,Matriz,10020,Impresora,123456111,Jose Martinez,5/08/24,600,3,1800
32,TIENDA01,Matriz,10020,Impresora,123456333,Jorge Mateus,27/01/24,600,3,1800

In [113]:
# slicing de filas no es inclusivo el lim superior
df.iloc[0:5, 6]

0    19/10/24
1    16/11/24
2    20/02/24
3     3/06/24
4     1/02/24
Name: FechaDeVenta, dtype: str

In [114]:
# slicing de filas no es inclusivo el lim superior
df.iloc[0:8, 0:5]

  CodigoTienda  Tienda  CodigoProducto DescripcionProduto  Matricula
0     TIENDA01  Matriz           10001         Smartphone  123456111
1     TIENDA01  Matriz           10001         Smartphone  123456111
2     TIENDA01  Matriz           10002             Tablet  123456333
3     TIENDA01  Matriz           10002             Tablet  123456333
4     TIENDA01  Matriz           10003          Televisor  123456333
5     TIENDA01  Matriz           10004           Lavadora  123456222
6     TIENDA01  Matriz           10005             Laptop  123456222
7     TIENDA01  Matriz           10005             Laptop  123456222

### `loc`

In [115]:
df.loc[11]

CodigoTienda                  TIENDA01
Tienda                          Matriz
CodigoProducto                   10010
DescripcionProduto    Freidor elétrico
Matricula                    123456222
NombreVendedor            Maria Garcia
FechaDeVenta                   6/03/24
PrecioUnitario                     250
Cantidad                             2
Valorventa                         500
Name: 11, dtype: object

In [116]:
# slicing de filas es inclusivo el lim superior
df.loc[10:20]

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
10,TIENDA01,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,3/03/24,250,1,250
11,TIENDA01,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,6/03/24,250,2,500
12,TIENDA01,Matriz,10011,Licuadora,123456111,Jose Martinez,7/08/24,80,1,80
13,TIENDA01,Matriz,10011,Licuadora,123456111,Jose Martinez,6/10/24,80,3,240
14,TIENDA01,Matriz,10012,Procesador de alimentos,123456222,Maria Garcia,11/05/24,180,1,180
15,TIENDA01,Matriz,10012,Procesador de alimentos,123456333,Jorge Mateus,21/12/24,180,2,360
16,TIENDA01,Matriz,10013,Estufa,123456111,Jose Martinez,28/02/24,600,3,1800
17,TIENDA01,Matriz,10013,Estufa,123456222,Maria Garcia,19/02/24,600,3,1800
18,TIENDA01,Matriz,10013,Estufa,123456333,Jorge Mateus,2/08/24,600,2,1200
19,TIENDA01,Matriz,10014,Refrigerador,123456222,Maria Garcia,26/04/24,1200,1,1200
20,TIENDA01,Matriz,10014,Refrigerador,123456222,Maria Garcia,11/06/24,1200,3,3600

In [117]:
df.loc[10:20, "DescripcionProduto"]

10           Freidor elétrico
11           Freidor elétrico
12                  Licuadora
13                  Licuadora
14    Procesador de alimentos
15    Procesador de alimentos
16                     Estufa
17                     Estufa
18                     Estufa
19               Refrigerador
20               Refrigerador
Name: DescripcionProduto, dtype: str

In [118]:
# slicing de filas es inclusivo el lim superior
df.loc[10:20, ["Tienda", "DescripcionProduto", "Cantidad"]]

    Tienda       DescripcionProduto  Cantidad
10  Matriz         Freidor elétrico         1
11  Matriz         Freidor elétrico         2
12  Matriz                Licuadora         1
13  Matriz                Licuadora         3
14  Matriz  Procesador de alimentos         1
15  Matriz  Procesador de alimentos         2
16  Matriz                   Estufa         3
17  Matriz                   Estufa         3
18  Matriz                   Estufa         2
19  Matriz             Refrigerador         1
20  Matriz             Refrigerador         3

In [119]:
# Slicing también con las columnas

df.loc[10:20, "Tienda":"Cantidad"]

,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad
10,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,3/03/24,250,1
11,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,6/03/24,250,2
12,Matriz,10011,Licuadora,123456111,Jose Martinez,7/08/24,80,1
13,Matriz,10011,Licuadora,123456111,Jose Martinez,6/10/24,80,3
14,Matriz,10012,Procesador de alimentos,123456222,Maria Garcia,11/05/24,180,1
15,Matriz,10012,Procesador de alimentos,123456333,Jorge Mateus,21/12/24,180,2
16,Matriz,10013,Estufa,123456111,Jose Martinez,28/02/24,600,3
17,Matriz,10013,Estufa,123456222,Maria Garcia,19/02/24,600,3
18,Matriz,10013,Estufa,123456333,Jorge Mateus,2/08/24,600,2
19,Matriz,10014,Refrigerador,123456222,Maria Garcia,26/04/24,1200,1
20,Matriz,10014,Refrigerador,123456222,Maria Garcia,11/06/24,1200,3

In [120]:
animales = {
    "animal" : ["cobra", "tigre", "león"],
    "velocidad" : [6, 30, 27],
    "veneno": ["si", "no", "no"],
    "tipo" : ["reptil", "felino", "felino"]
}

df_animales = pd.DataFrame(animales)

In [121]:
df_animales

  animal  velocidad veneno    tipo
0  cobra          6     si  reptil
1  tigre         30     no  felino
2   león         27     no  felino

df_anilames

# 🛠️ El Parámetro `inplace=True` en Pandas

Por defecto, la mayoría de las operaciones en Pandas (como `set_index`, `dropna`, o `rename`) **no modifican** el DataFrame original; en su lugar, devuelven una **copia** con los cambios aplicados.

### ¿Qué hace específicamente?
Cuando activas `inplace=True`, le das una instrucción directa a Pandas:
* **Modificación directa:** Los cambios se aplican sobre el objeto original (`df_animales`).
* **Sin retorno:** El método devuelve `None`. Por eso, si haces `df = df.set_index(..., inplace=True)`, tu variable `df` quedará vacía.

### Comparativa de uso

| Sin `inplace` (Recomendado) | Con `inplace=True` |
| :--- | :--- |
| `df = df.set_index("animal")` | `df.set_index("animal", inplace=True)` |
| Crea una copia y la reasigna. | Modifica el DataFrame existente. |
| Permite "encadenar" métodos (pipeline). | No permite encadenar más funciones. |

---

### ⚠️ Nota de Buenas Prácticas
Aunque es muy común encontrarlo en tutoriales, la comunidad de Data Science y los desarrolladores de Pandas recomiendan **no usarlo** por las siguientes razones:

1. **Legibilidad:** Es más claro ver `df = df.operacion()` para saber que la variable está cambiando.
2. **Consistencia:** No todos los métodos de Pandas tienen el parámetro `inplace`, lo que genera confusión.
3. **Depreciación:** Pandas está trabajando para eliminar este parámetro en versiones futuras (Pandas 3.0+), por lo que es mejor acostumbrarse a la reasignación.



### Ejemplo en el Notebook:
```python
# ✅ MEJOR PRÁCTICA (Nada de inplace=True)
df_animales = df_animales.set_index("animal")

# ❌ FORMA ANTIGUA
# df_animales.set_index("animal", inplace=True)

# 📉 ¿Qué pasa si no reasigno ni uso `inplace=True`?

Si ejecutas una operación como `df.set_index("animal")` por sí sola, sucede lo siguiente:

1. **Se crea una copia temporal:** Pandas procesa la instrucción y genera un nuevo DataFrame en la memoria RAM con el cambio aplicado.
2. **Se muestra en pantalla:** Como no guardaste ese resultado en ninguna parte, el Notebook simplemente te muestra una "vista previa" del resultado en la celda.
3. **El cambio se descarta:** Al terminar de ejecutarse la celda, esa copia temporal desaparece. Tu DataFrame original `df_animales` **sigue igual que al principio**.

### 🧪 Ejemplo del "Efecto Fantasma"

```python
# Escenario: Queremos cambiar el índice a la columna 'animal'

# ❌ ERROR COMÚN: La operación se ejecuta, se muestra, pero NO se guarda.
df_animales.set_index("animal") 

# Si revisas el DF en la siguiente celda, verás que NO tiene el nuevo índice.
print(df_animales.index)

In [122]:
df_animales.set_index("animal", inplace=True)

In [123]:
df_animales

        velocidad veneno    tipo
animal
cobra           6     si  reptil
tigre          30     no  felino
león           27     no  felino

In [ ]:
df_animales.loc["tigre"]

velocidad        30
veneno           no
tipo         felino
Name: tigre, dtype: object

In [ ]:
df_animales.loc["tigre", "velocidad"]

np.int64(30)

In [ ]:
df_animales.loc["cobra":"tigre", ["velocidad","tipo"]]

        velocidad    tipo
animal
cobra           6  reptil
tigre          30  felino

In [129]:
df_animales.loc[["león","cobra"],["tipo","veneno"]]

          tipo veneno
animal
león    felino     no
cobra   reptil     si