3. HTML | pd.read_html()
HTML significa HyperText Markup Language (Lenguaje de Marcado de Hipertexto) y es el lenguaje estándar que se utiliza para crear páginas web. El tipo de archivos HMTL está dado por la extensión .html.
El método pd.read_html() permite leer páginas web (usando los protocolos http, ftp y file de URL) en busca de tablas HTML, que son retornadas en una lista de objetos DataFrame. Algunos argumentos de interés son:

Cadena de texto o expresión regular a buscar en el contenido de las tablas. Si se especifica, solo las tablas que cumplan con esta condición serán cargadas. (match)

Etiquetas o atributos HTML usados para identificar una tabla en particular. (attrs)

Consultar la especificación de la función en la documentación oficial para más detalles sobre cómo usar estos argumentos.

Cuando se quiere extraer datos de un sitio de internet, utilizamos una técnica llamada web scraping.
Algunas limitaciones de este método son:

Busca únicamente datos en formato tabular.

En muchas ocasiones es necesario buscar en el codigo HTML con otras bibliotecas que simulen un navegador (requests), porque el sitio web puede bloquear la consulta directa con Pandas.

Dato importante: Para leer archivos con formato html con Pandas, es necesario tener instalada la biblioteca lxml.
pip install lxml
Sintaxis básica

In [11]:
import pandas as pd

In [15]:
df = pd.read_xml('datos_ventas.xml')

In [16]:
df.head()

,index,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000
2,2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
3,3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,3/06/24,1000,3,3000
4,4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500

6. Archivos JSON | pd.read_json()
JSON: JavaScript Obect Notation.

Es un archivo de texto.

Formato de archivos compacto y fácil de leer para las personas.

Comúnmente utilizado para intercambio de datos en la web y almacenamiento en bases de datos no relacionales (NoSQL).

In [18]:
df1 =pd.read_json ('anscombe.json')

In [19]:
df.head()

,index,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000
2,2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
3,3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,3/06/24,1000,3,3000
4,4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500

In [20]:
type(df1)

pandas.DataFrame