In [3]:
# Intalando libreria Panda
!pip install pandas

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
pd.__version__

'3.0.1'

In [6]:
# Archivo csv con delimitador ","
df = pd.read_csv(filepath_or_buffer="datasets/msft.csv", sep=",")

In [7]:
df.head()

        Date   Open   High    Low  Close    Volume  Adj. Close*
0  19-Sep-03  29.76  29.97  29.52  29.96  92433800        29.79
1  18-Sep-03  28.49  29.51  28.42  29.50  67268096        29.34
2  17-Sep-03  28.76  28.95  28.47  28.50  47221600        28.34
3  16-Sep-03  28.41  28.95  28.32  28.90  52060600        28.74
4  15-Sep-03  28.37  28.61  28.33  28.36  41432300        28.20

1.2. Cargando archivo CSV con separador ;

In [8]:
df1 = pd.read_csv(filepath_or_buffer="datasets/DatosVentas_punto_coma.csv", sep=";", encoding="utf-8")

In [9]:

df.head()

        Date   Open   High    Low  Close    Volume  Adj. Close*
0  19-Sep-03  29.76  29.97  29.52  29.96  92433800        29.79
1  18-Sep-03  28.49  29.51  28.42  29.50  67268096        29.34
2  17-Sep-03  28.76  28.95  28.47  28.50  47221600        28.34
3  16-Sep-03  28.41  28.95  28.32  28.90  52060600        28.74
4  15-Sep-03  28.37  28.61  28.33  28.36  41432300        28.20

In [11]:
df.tail()

         Date   Open   High    Low  Close    Volume  Adj. Close*
60  25-Jun-03  25.64  25.99  25.14  25.26  60483500        25.12
61  24-Jun-03  25.65  26.04  25.52  25.70  51820300        25.56
62  23-Jun-03  26.14  26.24  25.49  25.78  52584500        25.64
63  20-Jun-03  26.34  26.38  26.01  26.33  86048896        26.18
64  19-Jun-03  26.09  26.39  26.01  26.07  63626900        25.92

1.3. Cargando archivo TSV con separador TAB

In [19]:
df2 = pd.read_csv(filepath_or_buffer="datasets/DatosVentas_tab.tsv", sep="\t", encoding="latin-1")

In [17]:
df22 = pd.read_csv(
    r"C:\Users\User\Desktop\Analisis_Datos_Python\3. Material Curso Python\2. Cargando datos con Pandas\datasets\DatosVentas_tab.tsv",
    sep="\t",
    encoding="latin-1"
)

In [20]:
df2.head(3)

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,José Martinez,19/10/2024,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,José Martinez,16/11/2024,1500,2,3000
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/2024,1000,2,2000