# **<span style="color:red">Insertando Titulos en lenguaje Markoviano</span>**
Rojos y Naranjas
Red (Rojo puro)

Tomato (Rojo anaranjado, muy moderno)

Orange (Naranja vibrante)

DarkOrange (Naranja oscuro)

Crimson (Rojo carmesí, elegante)

🔵 Azules y Cianes
Blue (Azul fuerte)

SkyBlue (Azul cielo, más suave)

RoyalBlue (Azul real, muy profesional)

Cyan (Cian, brillante y tecnológico)

DeepSkyBlue (Azul profundo)

🟢 Verdes
Green (Verde estándar)

LimeGreen (Verde lima, resalta mucho)

SeaGreen (Verde mar, más oscuro y serio)

ForestGreen (Verde bosque)

Olive (Verde oliva)

🟣 Morados y Rosas
BlueViolet (Violeta azulado)

Magenta (Rosa fuerte/Fucsia)

Purple (Púrpura)

HotPink (Rosa brillante)

Orchid (Orquídea, un lila suave)

🟡 Amarillos y Dorados
Gold (Dorado, ideal para resaltar)

Yellow (Amarillo puro)

Khaki (Caqui, un amarillo tierra suave)


# **<span style="color:skyblue ">Métodos Y Propiedades</span>**
1.  <span style = "color:plum">[df|series].head() [df|series].tail()</span>

Permite cisualizar las primeras y ultimas observaciones del conjunto de datos

In [2]:
import pandas as pd

In [5]:
df= pd.read_csv("datos_ventas.csv", sep =";")

In [6]:
df.head()

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,3/06/24,1000,3,3000
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500

In [8]:
df.head(10)

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,3/06/24,1000,3,3000
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500
5,TIENDA01,Matriz,10004,Lavadora,123456222,Maria Garcia,30/05/24,2400,1,2400
6,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,29/10/24,3000,3,9000
7,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,24/11/24,3000,2,6000
8,TIENDA01,Matriz,10007,Mezclador,123456222,Maria Garcia,14/05/24,200,1,200
9,TIENDA01,Matriz,10008,Cafetera,123456222,Maria Garcia,5/07/24,240,1,240

In [9]:
df.tail()

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
28,TIENDA01,Matriz,10018,Colchón,123456111,Jose Martinez,22/12/24,310,2,620
29,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,13/04/24,310,3,930
30,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,10/09/24,310,3,930
31,TIENDA01,Matriz,10020,Impresora,123456111,Jose Martinez,5/08/24,600,3,1800
32,TIENDA01,Matriz,10020,Impresora,123456333,Jorge Mateus,27/01/24,600,3,1800

In [10]:
df.tail(10)

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
23,TIENDA01,Matriz,10016,Armario,123456111,Jose Martinez,24/03/24,1500,3,4500
24,TIENDA01,Matriz,10016,Armario,123456111,Jose Martinez,17/08/24,1500,2,3000
25,TIENDA01,Matriz,10016,Armario,123456111,Jose Martinez,11/10/24,1500,1,1500
26,TIENDA01,Matriz,10016,Armario,123456333,Jorge Mateus,24/01/24,1500,1,1500
27,TIENDA01,Matriz,10017,Cama,123456333,Jorge Mateus,16/09/24,2800,1,2800
28,TIENDA01,Matriz,10018,Colchón,123456111,Jose Martinez,22/12/24,310,2,620
29,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,13/04/24,310,3,930
30,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,10/09/24,310,3,930
31,TIENDA01,Matriz,10020,Impresora,123456111,Jose Martinez,5/08/24,600,3,1800
32,TIENDA01,Matriz,10020,Impresora,123456333,Jorge Mateus,27/01/24,600,3,1800

In [12]:
# Visualizar los valores de una columna específica como un array de NumPy
df["PrecioUnitario"].values

array([1500, 1500, 1000, 1000, 3500, 2400, 3000, 3000,  200,  240,  250,
        250,   80,   80,  180,  180,  600,  600,  600, 1200, 1200, 1200,
       1500, 1500, 1500, 1500, 1500, 2800,  310,  310,  310,  600,  600])

In [14]:
df.columns

Index(['CodigoTienda', 'Tienda', 'CodigoProducto', 'DescripcionProduto',
       'Matricula', 'NombreVendedor', 'FechaDeVenta', 'PrecioUnitario',
       'Cantidad', 'Valorventa'],
      dtype='str')

In [16]:
df["Cantidad"].values

array([1, 2, 2, 3, 3, 1, 3, 2, 1, 1, 1, 2, 1, 3, 1, 2, 3, 3, 2, 1, 3, 3,
       2, 3, 2, 1, 1, 1, 2, 3, 3, 3, 3])

 # 2. <span style = "color: plum"> [df|series].sample(n) </span>


Sirve para obsrvar datos de manera aleatoria las observaciones

In [19]:
df.sample(5)

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
23,TIENDA01,Matriz,10016,Armario,123456111,Jose Martinez,24/03/24,1500,3,4500
28,TIENDA01,Matriz,10018,Colchón,123456111,Jose Martinez,22/12/24,310,2,620
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
11,TIENDA01,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,6/03/24,250,2,500

2. <span style = "color: plum"> [df|series].shape(n) </span>

Propiedas para consultar el tamaño del conjunto de datos

In [22]:
df.shape
#Muestra una tupla con el número de filas y columnas del DataFrame. En este caso, (33, 10) indica que el DataFrame tiene 33 filas y 10  columnas.

(33, 10)

In [24]:
df["Cantidad"].shape

(33,)

In [27]:
num_filas= df.shape[0]
num_columnas= df.shape[1]
print(f"El DataFrame tiene {num_filas} filas y {num_columnas} columnas.")

El DataFrame tiene 33 filas y 10 columnas.

# 3. <span style = "color: plum"> [df|series].info
</span>

Este método permite generar un vistaso inicial  de la informacion general

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CodigoTienda        33 non-null     str
 1   Tienda              33 non-null     str
 2   CodigoProducto      33 non-null     int64
 3   DescripcionProduto  33 non-null     str
 4   Matricula           33 non-null     int64
 5   NombreVendedor      33 non-null     str
 6   FechaDeVenta        33 non-null     str
 7   PrecioUnitario      33 non-null     int64
 8   Cantidad            33 non-null     int64
 9   Valorventa          33 non-null     int64
dtypes: int64(5), str(5)
memory usage: 2.7 KB


#  4. <span style = "color: plum "> [df|series]. decribe() </span>

Realiza un resumen estadisco  descriptivo mas comunes para las variables cuantitativos

In [29]:
df.describe().round(0)

       CodigoProducto    Matricula  PrecioUnitario  Cantidad  Valorventa
count            33.0         33.0            33.0      33.0        33.0
mean          10011.0  123456219.0          1097.0       2.0      2274.0
std               6.0         90.0           946.0       1.0      2383.0
min           10001.0  123456111.0            80.0       1.0        80.0
25%           10007.0  123456111.0           310.0       1.0       620.0
50%           10013.0  123456222.0          1000.0       2.0      1800.0
75%           10016.0  123456333.0          1500.0       3.0      3000.0
max           10020.0  123456333.0          3500.0       3.0     10500.0

### Transponiendo la matriz

In [30]:
df.describe().round(0).T

,count,mean,std,min,25%,50%,75%,max
CodigoProducto,33.0,10011.0,6.0,10001.0,10007.0,10013.0,10016.0,10020.0
Matricula,33.0,123456219.0,90.0,123456111.0,123456111.0,123456222.0,123456333.0,123456333.0
PrecioUnitario,33.0,1097.0,946.0,80.0,310.0,1000.0,1500.0,3500.0
Cantidad,33.0,2.0,1.0,1.0,1.0,2.0,3.0,3.0
Valorventa,33.0,2274.0,2383.0,80.0,620.0,1800.0,3000.0,10500.0

In [41]:
type(df["PrecioUnitario"].describe())

pandas.Series

## Conviertiendo una serie a un DataFrame

In [51]:
df["PrecioUnitario"].describe().to_frame().round(0)

       PrecioUnitario
count            33.0
mean           1097.0
std             946.0
min              80.0
25%             310.0
50%            1000.0
75%            1500.0
max            3500.0

#  <span style = "color: plum">  5. df.nlargest (n, columns) | df.nsmallest(n, columns) </span>

In [53]:
df.columns

Index(['CodigoTienda', 'Tienda', 'CodigoProducto', 'DescripcionProduto',
       'Matricula', 'NombreVendedor', 'FechaDeVenta', 'PrecioUnitario',
       'Cantidad', 'Valorventa'],
      dtype='str')

In [52]:
df.nlargest(5, "PrecioUnitario")

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500
6,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,29/10/24,3000,3,9000
7,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,24/11/24,3000,2,6000
27,TIENDA01,Matriz,10017,Cama,123456333,Jorge Mateus,16/09/24,2800,1,2800
5,TIENDA01,Matriz,10004,Lavadora,123456222,Maria Garcia,30/05/24,2400,1,2400

In [55]:
df.nlargest(5, "Valorventa")

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500
6,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,29/10/24,3000,3,9000
7,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,24/11/24,3000,2,6000
23,TIENDA01,Matriz,10016,Armario,123456111,Jose Martinez,24/03/24,1500,3,4500
20,TIENDA01,Matriz,10014,Refrigerador,123456222,Maria Garcia,11/06/24,1200,3,3600

In [64]:
df.nsmallest(5, ["Cantidad", "Valorventa"])

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
12,TIENDA01,Matriz,10011,Licuadora,123456111,Jose Martinez,7/08/24,80,1,80
14,TIENDA01,Matriz,10012,Procesador de alimentos,123456222,Maria Garcia,11/05/24,180,1,180
8,TIENDA01,Matriz,10007,Mezclador,123456222,Maria Garcia,14/05/24,200,1,200
9,TIENDA01,Matriz,10008,Cafetera,123456222,Maria Garcia,5/07/24,240,1,240
10,TIENDA01,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,3/03/24,250,1,250

#  <span style = "color: plum">  5. df.idemax (n) | df.idemax(n) </span>
Devuelve el indice del valor mayor  o el menor

In [65]:
df.idxmax()

CodigoTienda           0
Tienda                 0
CodigoProducto        31
DescripcionProduto     4
Matricula              2
NombreVendedor         5
FechaDeVenta          12
PrecioUnitario         4
Cantidad               3
Valorventa             4
dtype: int64

In [66]:
df.idxmin()

CodigoTienda           0
Tienda                 0
CodigoProducto         0
DescripcionProduto    22
Matricula              0
NombreVendedor         2
FechaDeVenta           4
PrecioUnitario        12
Cantidad               0
Valorventa            12
dtype: int64

In [69]:
df["PrecioUnitario"].idxmax()

4

In [72]:
df.nlargest(1, "PrecioUnitario")

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500

In [70]:
df["PrecioUnitario"].idxmin()

12

In [73]:
df.nsmallest(1, "PrecioUnitario")

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
12,TIENDA01,Matriz,10011,Licuadora,123456111,Jose Martinez,7/08/24,80,1,80

# <span style= "color: Plum">  6. df.isnull() | df.isna() </span>
Estos dos métodos realizan exactamente la misma función, poder identificar valores faltantes
 No incluye valores faltantes como los string " "

In [ ]:
df.isna()
#Si hay un true, significa que hay al menos un valor faltante en esa columna. Si es False, no hay valores faltantes en esa columna.

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False

In [77]:
df.isna().sum()

CodigoTienda          0
Tienda                0
CodigoProducto        0
DescripcionProduto    0
Matricula             0
NombreVendedor        0
FechaDeVenta          0
PrecioUnitario        0
Cantidad              0
Valorventa            0
dtype: int64

In [79]:
# Conociendo en valores porcentuales de valores faltantes en cada columna
valores_faltantes = df.isna().sum()/df.shape[0]*100
print(valores_faltantes)

CodigoTienda          0.0
Tienda                0.0
CodigoProducto        0.0
DescripcionProduto    0.0
Matricula             0.0
NombreVendedor        0.0
FechaDeVenta          0.0
PrecioUnitario        0.0
Cantidad              0.0
Valorventa            0.0
dtype: float64

#  <span style = "color: plum"> 7. series.unique()| df[Series].nunqui() |df[Series].value_counts() </span>

Cunado s etrata de variables categoricad , es necesario encontrar informacion acerca de las categorias posibles que puede tomar una variable

In [ ]:
# Este solo se en una sedf["DescripcionProduto"].unique()

<StringArray>
[             'Smartphone',                  'Tablet',
               'Televisor',                'Lavadora',
                  'Laptop',               'Mezclador',
                'Cafetera',        'Freidor elétrico',
               'Licuadora', 'Procesador de alimentos',
                  'Estufa',            'Refrigerador',
                 'Armario',                    'Cama',
                 'Colchón',               'Impresora']
Length: 16, dtype: str

In [82]:
df.nunique()

CodigoTienda           1
Tienda                 1
CodigoProducto        16
DescripcionProduto    16
Matricula              3
NombreVendedor         3
FechaDeVenta          32
PrecioUnitario        14
Cantidad               3
Valorventa            21
dtype: int64

In [86]:
df["DescripcionProduto"].nunique()

16

In [ ]:
# DEfine cuantas veces se repite cada valor único en la columna "DescripcionProduto"
df["DescripcionProduto"].value_counts()

DescripcionProduto
Armario                    5
Estufa                     3
Refrigerador               3
Colchón                    3
Smartphone                 2
Tablet                     2
Laptop                     2
Freidor elétrico           2
Licuadora                  2
Procesador de alimentos    2
Impresora                  2
Televisor                  1
Lavadora                   1
Mezclador                  1
Cafetera                   1
Cama                       1
Name: count, dtype: int64

In [91]:
df.value_counts().to_frame()

                                                                                                                                     count
CodigoTienda Tienda CodigoProducto DescripcionProduto      Matricula NombreVendedor FechaDeVenta PrecioUnitario Cantidad Valorventa
TIENDA01     Matriz 10001          Smartphone              123456111 Jose Martinez  19/10/24     1500           1        1500            1
                                                                                    16/11/24     1500           2        3000            1
                    10002          Tablet                  123456333 Jorge Mateus   20/02/24     1000           2        2000            1
                                                                                    3/06/24      1000           3        3000            1
                    10003          Televisor               123456333 Jorge Mateus   1/02/24      3500           3        10500           1
                    10004          Lavadora                123456222 Maria Garcia   30/05/24     2400           1        2400            1
                    10005          Laptop                  123456222 Maria Garcia   29/10/24     3000           3        9000            1
                                                                                    24/11/24     3000           2        6000            1
                    10007          Mezclador               123456222 Maria Garcia   14/05/24     200            1        200             1
                    10008          Cafetera                123456222 Maria Garcia   5/07/24      240            1        240             1
                    10010          Freidor elétrico        123456222 Maria Garcia   3/03/24      250            1        250             1
                                                                                    6/03/24      250            2        500             1
                    10011          Licuadora               123456111 Jose Martinez  7/08/24      80             1        80              1
                                                                                    6/10/24      80             3        240             1
                    10012          Procesador de alimentos 123456222 Maria Garcia   11/05/24     180            1        180             1
                                                           123456333 Jorge Mateus   21/12/24     180            2        360             1
                    10013          Estufa                  123456111 Jose Martinez  28/02/24     600            3        1800            1
                                                           123456222 Maria Garcia   19/02/24     600            3        1800            1
                                                           123456333 Jorge Mateus   2/08/24      600            2        1200            1
                    10014          Refrigerador            123456222 Maria Garcia   26/04/24     1200           1        1200            1
                                                                                    11/06/24     1200           3        3600            1
                                                                                    16/11/24     1200           3        3600            1
                    10016          Armario                 123456111 Jose Martinez  2/01/24      1500           2        3000            1
                                                                                    24/03/24     1500           3        4500            1
                                                                                    17/08/24     1500           2        3000            1
                                                                                    11/10/24     1500           1        1500            1
                                                           123456333 Jorge Mateus   24/01/24     1500           1        1500            1
                    10017          Cama                    123456333 Jorge Mateus   16/09/24     2800           1        2800            1
                    10018          Colchón                 123456111 Jose Martinez  22/12/24     310            2        620             1
                                                           123456333 Jorge Mateus   13/04/24     310            3        930             1
                                                                                    10/09/24     310            3        930             1
                    10020          Impresora               123456111 Jose Martinez  5/08/24      600            3        1800            1
                                                           123456333 Jorge Mateus   27/01/24     600            3        1800            1

# **<span style = "color: plum"> 8. Accediendo a Filas y Columnas </span>**

#  <span style = "color: plum"> Metodos iloc y loc </span>
1. ¿Cuál elegir?
Usa loc: Cuando conoces los nombres (etiquetas) de tus filas o columnas. Es el más humano y fácil de leer.

Usa iloc: Cuando conoces la posición (el orden numérico). Es ideal para cuando quieres "las primeras 5 filas" o "la última columna".

2. La regla del Rango (Abierto vs. Cerrado)
Esta es la parte donde la mayoría se equivoca. Memoriza esto:

loc es INCLUSIVO (Cerrado): Se incluye tanto el inicio como el final.

40:50 te da 11 filas (de la 40 a la 50 inclusive).

iloc es EXCLUSIVO (Abierto): Como las listas de Python, el final no se incluye.

40:50 te da 10 filas (de la 40 a la 49).

3. Ejemplos Prácticos
Imagina que tu columna se llama "edad" y es la columna número 3 (índice 2).

Por Nombre (loc)
Comando: df.loc[40:50, 'edad']

Filas: Trae desde la etiqueta 40 hasta la 50.

Columna: Busca específicamente la palabra 'edad'.

Por Posición (iloc)
Comando: df.iloc[40:51, 2]

Filas: Trae desde la posición 40 hasta la 50 (ponemos 51 para que incluya la 50).

Columna: Trae la columna en la posición 2 (la tercera).

In [ ]:
# Solo funciona si el nombre de la columna no tiene espacios

df.Matricula.head()

0    123456111
1    123456111
2    123456333
3    123456333
4    123456333
Name: Matricula, dtype: int64

In [94]:
df.columns

Index(['CodigoTienda', 'Tienda', 'CodigoProducto', 'DescripcionProduto',
       'Matricula', 'NombreVendedor', 'FechaDeVenta', 'PrecioUnitario',
       'Cantidad', 'Valorventa'],
      dtype='str')

In [98]:
df[["CodigoTienda","Tienda","Cantidad"]]

   CodigoTienda  Tienda  Cantidad
0      TIENDA01  Matriz         1
1      TIENDA01  Matriz         2
2      TIENDA01  Matriz         2
3      TIENDA01  Matriz         3
4      TIENDA01  Matriz         3
5      TIENDA01  Matriz         1
6      TIENDA01  Matriz         3
7      TIENDA01  Matriz         2
8      TIENDA01  Matriz         1
9      TIENDA01  Matriz         1
10     TIENDA01  Matriz         1
11     TIENDA01  Matriz         2
12     TIENDA01  Matriz         1
13     TIENDA01  Matriz         3
14     TIENDA01  Matriz         1
15     TIENDA01  Matriz         2
16     TIENDA01  Matriz         3
17     TIENDA01  Matriz         3
18     TIENDA01  Matriz         2
19     TIENDA01  Matriz         1
20     TIENDA01  Matriz         3
21     TIENDA01  Matriz         3
22     TIENDA01  Matriz         2
23     TIENDA01  Matriz         3
24     TIENDA01  Matriz         2
25     TIENDA01  Matriz         1
26     TIENDA01  Matriz         1
27     TIENDA01  Matriz         1
28     TIENDA01  Matriz         2
29     TIENDA01  Matriz         3
30     TIENDA01  Matriz         3
31     TIENDA01  Matriz         3
32     TIENDA01  Matriz         3

## Iloc

In [99]:
df.iloc[3]

CodigoTienda              TIENDA01
Tienda                      Matriz
CodigoProducto               10002
DescripcionProduto          Tablet
Matricula                123456333
NombreVendedor        Jorge Mateus
FechaDeVenta               3/06/24
PrecioUnitario                1000
Cantidad                         3
Valorventa                    3000
Name: 3, dtype: object

In [100]:
df.iloc[0:2]

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000

In [101]:
df.iloc[25::]

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
25,TIENDA01,Matriz,10016,Armario,123456111,Jose Martinez,11/10/24,1500,1,1500
26,TIENDA01,Matriz,10016,Armario,123456333,Jorge Mateus,24/01/24,1500,1,1500
27,TIENDA01,Matriz,10017,Cama,123456333,Jorge Mateus,16/09/24,2800,1,2800
28,TIENDA01,Matriz,10018,Colchón,123456111,Jose Martinez,22/12/24,310,2,620
29,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,13/04/24,310,3,930
30,TIENDA01,Matriz,10018,Colchón,123456333,Jorge Mateus,10/09/24,310,3,930
31,TIENDA01,Matriz,10020,Impresora,123456111,Jose Martinez,5/08/24,600,3,1800
32,TIENDA01,Matriz,10020,Impresora,123456333,Jorge Mateus,27/01/24,600,3,1800

In [103]:
df.iloc[0:5,6]

0    19/10/24
1    16/11/24
2    20/02/24
3     3/06/24
4     1/02/24
Name: FechaDeVenta, dtype: str

In [104]:
df.iloc[0:8,0:5]

  CodigoTienda  Tienda  CodigoProducto DescripcionProduto  Matricula
0     TIENDA01  Matriz           10001         Smartphone  123456111
1     TIENDA01  Matriz           10001         Smartphone  123456111
2     TIENDA01  Matriz           10002             Tablet  123456333
3     TIENDA01  Matriz           10002             Tablet  123456333
4     TIENDA01  Matriz           10003          Televisor  123456333
5     TIENDA01  Matriz           10004           Lavadora  123456222
6     TIENDA01  Matriz           10005             Laptop  123456222
7     TIENDA01  Matriz           10005             Laptop  123456222

## Loc

In [105]:
df.loc[11]

CodigoTienda                  TIENDA01
Tienda                          Matriz
CodigoProducto                   10010
DescripcionProduto    Freidor elétrico
Matricula                    123456222
NombreVendedor            Maria Garcia
FechaDeVenta                   6/03/24
PrecioUnitario                     250
Cantidad                             2
Valorventa                         500
Name: 11, dtype: object

In [ ]:
# REl limite superior no es incluido, por eso se muestra hasta el indice 20 y no el 21
df.loc[10:20]

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
10,TIENDA01,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,3/03/24,250,1,250
11,TIENDA01,Matriz,10010,Freidor elétrico,123456222,Maria Garcia,6/03/24,250,2,500
12,TIENDA01,Matriz,10011,Licuadora,123456111,Jose Martinez,7/08/24,80,1,80
13,TIENDA01,Matriz,10011,Licuadora,123456111,Jose Martinez,6/10/24,80,3,240
14,TIENDA01,Matriz,10012,Procesador de alimentos,123456222,Maria Garcia,11/05/24,180,1,180
15,TIENDA01,Matriz,10012,Procesador de alimentos,123456333,Jorge Mateus,21/12/24,180,2,360
16,TIENDA01,Matriz,10013,Estufa,123456111,Jose Martinez,28/02/24,600,3,1800
17,TIENDA01,Matriz,10013,Estufa,123456222,Maria Garcia,19/02/24,600,3,1800
18,TIENDA01,Matriz,10013,Estufa,123456333,Jorge Mateus,2/08/24,600,2,1200
19,TIENDA01,Matriz,10014,Refrigerador,123456222,Maria Garcia,26/04/24,1200,1,1200
20,TIENDA01,Matriz,10014,Refrigerador,123456222,Maria Garcia,11/06/24,1200,3,3600

In [114]:
df.loc[10:20, [ "Tienda","DescripcionProduto"]]

    Tienda       DescripcionProduto
10  Matriz         Freidor elétrico
11  Matriz         Freidor elétrico
12  Matriz                Licuadora
13  Matriz                Licuadora
14  Matriz  Procesador de alimentos
15  Matriz  Procesador de alimentos
16  Matriz                   Estufa
17  Matriz                   Estufa
18  Matriz                   Estufa
19  Matriz             Refrigerador
20  Matriz             Refrigerador

In [117]:
animales ={
    "animal":[ "perro","gato","conejo"],
    "velocidad":[ "lento","rapido","lento"],
    "veneno":[ "no","no","si"],
    "especie":[ "mamifero","mamifero","mamifero"]

}

In [119]:
df_animales = pd.DataFrame(animales)
df_animales

   animal velocidad veneno   especie
0   perro     lento     no  mamifero
1    gato    rapido     no  mamifero
2  conejo     lento     si  mamifero

In [124]:
df_animales.set_index("animal" , inplace=True)
df_animales

       velocidad veneno   especie
animal
perro      lento     no  mamifero
gato      rapido     no  mamifero
conejo     lento     si  mamifero

In [127]:
df_animales.loc["perro" : "gato",["velocidad","veneno"]]

       velocidad veneno
animal
perro      lento     no
gato      rapido     no