# <span style="color: plum;">TRATAMIENTO DE DATOS</span>

## <span style="color: plum;">CARGANDO  DATOS</span>

Como buena practica generar una copia del DataFrame

In [9]:
import pandas as pd

In [10]:
df_Original = pd.read_csv("datasets/base_ventas.csv", sep=";"   )

In [11]:
df_Original.head()

,matricula_funcionario,Nombre Funcionario,Cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,Categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,"210,9","404,1",1,NaN,28/09/20 16:19,5/10/20 16:31
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,"109,9","249,9",1,NaN,7/03/20 12:47,8/03/20 12:47
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,"699,9","1346,9",1,NaN,21/04/19 10:48,23/04/19 15:55
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,"899,9","1676,9",1,NaN,7/05/20 17:59,8/05/20 14:31
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099,"1709,1",1,"0,05",14/08/19 16:56,19/08/19 15:52

In [12]:
df_Original.tail()

,matricula_funcionario,Nombre Funcionario,Cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,Categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspiradora de piso,Casa,"88,9","189,9",3,NaN,4/11/19 15:40,5/11/19 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Licuadora,Cocina,"59,9","142,4",3,NaN,24/06/19 9:04,24/06/19 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batidora,Cocina,"49,9","95,9",3,NaN,8/08/20 14:46,9/08/20 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Freidora eléctrica,Cocina,"187,9",340,3,NaN,19/12/19 9:21,19/12/19 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina de lavar ropa,Electrodomésticos,1099,"1709,1",3,"0,09",18/03/19 15:40,23/03/19 17:52

# <span style = "color: blue"> Copiando DataFrame </span>

### 📝 Resumen: ¿Por qué usar `.copy()` en Pandas?

Usar `df = df_original.copy()` es una **regla de oro** en el análisis de datos por las siguientes razones:



#### 1. Independencia Total (Evita el "Efecto Espejo")
* **Sin `.copy()`:** Si haces `df = df_original`, ambos nombres apuntan a los **mismos datos**. Lo que borres o cambies en uno, afectará automáticamente al otro.
* **Con `.copy()`:** Creas un objeto nuevo e independiente. Si "rompes" el nuevo `df`, tus datos originales permanecen a salvo.

#### 2. Adiós al `SettingWithCopyWarning`
Pandas lanza este aviso cuando no está seguro si estás modificando una copia o el original. Al usar `.copy()`, le confirmas a Python que el objeto es independiente, eliminando avisos confusos.

#### 3. Flujo de Trabajo Seguro
Mantiene los datos "crudos" en memoria. Si te equivocas limpiando los datos, no necesitas volver a cargar el archivo (CSV/Excel) desde el disco; simplemente vuelves a ejecutar la copia y empiezas de nuevo.

---

**Ejemplo de uso:**
```python
# Mantiene el original intacto para emergencias
df_limpio = df_original.copy() 

# Ahora puedes trabajar sin miedo
df_limpio.dropna(inplace=True)

In [13]:
df = df_Original.copy()

In [14]:
df_Original.drop(columns=["comision"], inplace=True)

### 🗑️ Método `.drop()` en Pandas

El método **`.drop()`** se utiliza para eliminar filas o columnas de un DataFrame.

#### Desglose del comando:
`df.drop(columns=["nombre"], inplace=True)`

* **`columns=["nombre"]`**: Especifica la columna (o lista de columnas) que deseas eliminar.
* **`inplace=True`**: Modifica el DataFrame original directamente. Si no se usa, Pandas genera una copia con el cambio pero no altera el original.

---
**Diferencia entre Axis:**
* Aunque usar `columns=` es más moderno, a veces verás `axis=1`. Ambos significan lo mismo:
    * `axis=1` o `columns`: Se refiere a **Columnas** (vertical).
    * `axis=0` o `index`: Se refiere a **Filas** (horizontal).

**Ejemplo:**
```python
# Borra la columna 'comision' definitivamente
df_Original.drop(columns=["comision"], inplace=True)

In [15]:
df_Original.head()

,matricula_funcionario,Nombre Funcionario,Cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,Categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,"210,9","404,1",1,28/09/20 16:19,5/10/20 16:31
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,"109,9","249,9",1,7/03/20 12:47,8/03/20 12:47
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,"699,9","1346,9",1,21/04/19 10:48,23/04/19 15:55
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,"899,9","1676,9",1,7/05/20 17:59,8/05/20 14:31
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099,"1709,1",1,14/08/19 16:56,19/08/19 15:52

## <span style="color: plum;">Modificando el Nombre de las Columnas (Estandarizar)</span>

In [16]:
df.columns

Index(['matricula_funcionario', 'Nombre Funcionario', 'Cargo', 'codigo_tienda',
       'nombre_tienda', 'codigo_producto', 'descripcion_producto', 'Categoria',
       'precio_costo', 'valor_unitario', 'cantidad', 'comision', 'dt_venta',
       'dt_entrega'],
      dtype='str')

## Reemplazando los espacios por guinos bajo

In [17]:

#Estandarizando con snake_case

nombre_columnas= ['matricula_funcionario', 'nombre_funcionario', 'cargo', 'codigo_tienda',
       'nombre_tienda', 'codigo_producto', 'descripcion_producto', 'categoria',
       'precio_costo', 'valor_unitario', 'cantidad','comision', 'dt_venta', 'dt_entrega']

## Cambiando el nombre de las columnas

In [18]:
df.columns = nombre_columnas

### 🏷️ Renombrar columnas masivamente

El comando `df.columns = lista_de_nombres` se utiliza para asignar nuevos títulos a todas las columnas de un DataFrame de forma simultánea.

#### Características clave:
* **Orden posicional:** El primer nombre de la lista se asignará a la primera columna, el segundo a la segunda, etc.
* **Requisito de longitud:** La lista debe tener el mismo número de elementos que el DataFrame original.
* **Rapidez:** Es ideal cuando los nombres originales vienen mal (por ejemplo, con espacios o caracteres extraños) y quieres limpiarlos todos de una vez.

---
**Ejemplo de uso:**
```python
# Definimos los nuevos nombres
nuevos_nombres = ['fecha', 'producto', 'cantidad', 'precio']

# Los aplicamos al DataFrame
df.columns = nuevos_nombres

In [19]:
df.columns

Index(['matricula_funcionario', 'nombre_funcionario', 'cargo', 'codigo_tienda',
       'nombre_tienda', 'codigo_producto', 'descripcion_producto', 'categoria',
       'precio_costo', 'valor_unitario', 'cantidad', 'comision', 'dt_venta',
       'dt_entrega'],
      dtype='str')

In [20]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,"210,9","404,1",1,NaN,28/09/20 16:19,5/10/20 16:31
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,"109,9","249,9",1,NaN,7/03/20 12:47,8/03/20 12:47
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,"699,9","1346,9",1,NaN,21/04/19 10:48,23/04/19 15:55
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,"899,9","1676,9",1,NaN,7/05/20 17:59,8/05/20 14:31
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099,"1709,1",1,"0,05",14/08/19 16:56,19/08/19 15:52

In [21]:

df.nombre_funcionario[0]

'José María'

# <span style = "color: Plum" > Modificando los tipos de datos </span>

## <span style = "color: plum ">  Str a Float </span>

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nombre_funcionario     3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_tienda          3000 non-null   str
 4   nombre_tienda          3000 non-null   str
 5   codigo_producto        3000 non-null   int64
 6   descripcion_producto   3000 non-null   str
 7   categoria              3000 non-null   str
 8   precio_costo           3000 non-null   str
 9   valor_unitario         3000 non-null   str
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    str
 12  dt_venta               3000 non-null   str
 13  dt_entrega             3000 non-null   str
dtypes: int64(3), str(11)
memory usage: 328.3 KB

In [23]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,"210,9","404,1",1,NaN,28/09/20 16:19,5/10/20 16:31
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,"109,9","249,9",1,NaN,7/03/20 12:47,8/03/20 12:47
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,"699,9","1346,9",1,NaN,21/04/19 10:48,23/04/19 15:55
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,"899,9","1676,9",1,NaN,7/05/20 17:59,8/05/20 14:31
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099,"1709,1",1,"0,05",14/08/19 16:56,19/08/19 15:52

In [24]:
df["matricula_funcionario"] = df["matricula_funcionario"].astype("str")

### 🔢 Conversión de tipos con `.astype()`

El método **`.astype()`** se usa para cambiar el tipo de dato de una columna (por ejemplo, de número a texto).

#### Caso común: Convertir a String (`str`)
`df["columna"] = df["columna"].astype("str")`

* **¿Para qué sirve?**: Muy útil para columnas que contienen IDs, códigos postales, números de teléfono o matrículas. 
* **Importancia**: Evita que se pierdan ceros iniciales (ej: "0800") y previene errores al intentar realizar operaciones matemáticas en datos que solo sirven como identificadores.
* **Nota**: Debes reasignar la columna (`df["col"] = ...`) para que el cambio sea permanente en el DataFrame.

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   str
 1   nombre_funcionario     3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_tienda          3000 non-null   str
 4   nombre_tienda          3000 non-null   str
 5   codigo_producto        3000 non-null   int64
 6   descripcion_producto   3000 non-null   str
 7   categoria              3000 non-null   str
 8   precio_costo           3000 non-null   str
 9   valor_unitario         3000 non-null   str
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    str
 12  dt_venta               3000 non-null   str
 13  dt_entrega             3000 non-null   str
dtypes: int64(2), str(12)
memory usage: 328.3 KB

In [26]:
df["codigo_producto"] = df["codigo_producto"].astype("str")

In [27]:
df["codigo_producto"].info()

<class 'pandas.Series'>
RangeIndex: 3000 entries, 0 to 2999
Series name: codigo_producto
Non-Null Count  Dtype
--------------  -----
3000 non-null   str
dtypes: str(1)
memory usage: 23.6 KB

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   str
 1   nombre_funcionario     3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_tienda          3000 non-null   str
 4   nombre_tienda          3000 non-null   str
 5   codigo_producto        3000 non-null   str
 6   descripcion_producto   3000 non-null   str
 7   categoria              3000 non-null   str
 8   precio_costo           3000 non-null   str
 9   valor_unitario         3000 non-null   str
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    str
 12  dt_venta               3000 non-null   str
 13  dt_entrega             3000 non-null   str
dtypes: int64(1), str(13)
memory usage: 328.3 KB

In [29]:
df.precio_costo
#Recuerda en Pyton el punto significa el valor flotante, no el separador de miles. Si quieres convertir a entero, primero debes convertir a float y luego a int.

0       210,9
1       109,9
2       699,9
3       899,9
4        1099
        ...
2995     88,9
2996     59,9
2997     49,9
2998    187,9
2999     1099
Name: precio_costo, Length: 3000, dtype: str

In [30]:
#print(float("210.9"))
df["precio_costo"] = df["precio_costo"].str.replace(",",".")
df["valor_unitario"]= df["valor_unitario"].str.replace(",",".")

In [31]:
df.precio_costo

0       210.9
1       109.9
2       699.9
3       899.9
4        1099
        ...
2995     88.9
2996     59.9
2997     49.9
2998    187.9
2999     1099
Name: precio_costo, Length: 3000, dtype: str

In [32]:
df.valor_unitario

0        404.1
1        249.9
2       1346.9
3       1676.9
4       1709.1
         ...
2995     189.9
2996     142.4
2997      95.9
2998       340
2999    1709.1
Name: valor_unitario, Length: 3000, dtype: str

In [33]:
#Cambiamos a tipo numérico
df = df.astype({"precio_costo":"float", "valor_unitario":"float"})

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   str
 1   nombre_funcionario     3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_tienda          3000 non-null   str
 4   nombre_tienda          3000 non-null   str
 5   codigo_producto        3000 non-null   str
 6   descripcion_producto   3000 non-null   str
 7   categoria              3000 non-null   str
 8   precio_costo           3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    str
 12  dt_venta               3000 non-null   str
 13  dt_entrega             3000 non-null   str
dtypes: float64(2), int64(1), str(11)
memory usage: 328.3 KB

In [35]:
df.comision

0        NaN
1        NaN
2        NaN
3        NaN
4       0,05
        ...
2995     NaN
2996     NaN
2997     NaN
2998     NaN
2999    0,09
Name: comision, Length: 3000, dtype: str

## Modificando tipo para Date a Datetime

In [36]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,NaN,28/09/20 16:19,5/10/20 16:31
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,NaN,7/03/20 12:47,8/03/20 12:47
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,NaN,21/04/19 10:48,23/04/19 15:55
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,NaN,7/05/20 17:59,8/05/20 14:31
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,"0,05",14/08/19 16:56,19/08/19 15:52

In [37]:
df.dt_venta

0       28/09/20 16:19
1        7/03/20 12:47
2       21/04/19 10:48
3        7/05/20 17:59
4       14/08/19 16:56
             ...
2995     4/11/19 15:40
2996     24/06/19 9:04
2997     8/08/20 14:46
2998     19/12/19 9:21
2999    18/03/19 15:40
Name: dt_venta, Length: 3000, dtype: str

In [38]:
df["dt_venta"] = pd.to_datetime(df["dt_venta"],     format = "%d/%m/%y  %H:%M")
df["dt_entrega"] = pd.to_datetime(df["dt_entrega"], format ="%d/%m/%y %H:%M")

In [39]:
df.dt_entrega

0      2020-10-05 16:31:00
1      2020-03-08 12:47:00
2      2019-04-23 15:55:00
3      2020-05-08 14:31:00
4      2019-08-19 15:52:00
               ...
2995   2019-11-05 10:40:00
2996   2019-06-24 10:50:00
2997   2020-08-09 14:07:00
2998   2019-12-19 10:51:00
2999   2019-03-23 17:52:00
Name: dt_entrega, Length: 3000, dtype: datetime64[us]

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   str
 1   nombre_funcionario     3000 non-null   str
 2   cargo                  3000 non-null   str
 3   codigo_tienda          3000 non-null   str
 4   nombre_tienda          3000 non-null   str
 5   codigo_producto        3000 non-null   str
 6   descripcion_producto   3000 non-null   str
 7   categoria              3000 non-null   str
 8   precio_costo           3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    str
 12  dt_venta               3000 non-null   datetime64[us]
 13  dt_entrega             3000 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(2), int64(1), str(9)
memory usage: 328.3 KB

# <span style = "color : plum" > Consultando partes de una fecha </span>

In [41]:
#Conocer mes
df["dt_entrega"].dt.month

0       10
1        3
2        4
3        5
4        8
        ..
2995    11
2996     6
2997     8
2998    12
2999     3
Name: dt_entrega, Length: 3000, dtype: int32

In [42]:
#Año, v
df["dt_entrega"].dt.year

0       2020
1       2020
2       2019
3       2020
4       2019
        ...
2995    2019
2996    2019
2997    2020
2998    2019
2999    2019
Name: dt_entrega, Length: 3000, dtype: int32

# <span style ="color : plum" > Ingeniería de atributos (Feature Engineering) </span>
* Tratar datos faltantes
* Eliminar atributos
* Adicionar atributos
* Eliminar outliers
* Normalizar y estandarizar variables numéricas
* Tratar variables categóricas
* Entre otros...

## Identificando y tratando vlores faltantes (missing values)

In [43]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00

In [44]:
df.isnull().sum()

matricula_funcionario       0
nombre_funcionario          0
cargo                       0
codigo_tienda               0
nombre_tienda               0
codigo_producto             0
descripcion_producto        0
categoria                   0
precio_costo                0
valor_unitario              0
cantidad                    0
comision                 2841
dt_venta                    0
dt_entrega                  0
dtype: int64

In [45]:
df.isnull().sum()/df.shape[0]*100

matricula_funcionario     0.0
nombre_funcionario        0.0
cargo                     0.0
codigo_tienda             0.0
nombre_tienda             0.0
codigo_producto           0.0
descripcion_producto      0.0
categoria                 0.0
precio_costo              0.0
valor_unitario            0.0
cantidad                  0.0
comision                 94.7
dt_venta                  0.0
dt_entrega                0.0
dtype: float64

## Rellenado Valores Faltantes
## Método fillna()

In [46]:
# Este metodo aplica a todas las columnas, 
# se reemplaza el valor nulo por el valor que le indiquemos. En este caso 0.   
df.fillna(0).head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,0,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,0,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,0,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,0,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00

In [47]:
#Aqui si se esta aplicando solo a la columna comision, se reemplaza el valor nulo por el valor que le indiquemos. En este caso 0.
df["comision"].fillna(0).head()

0       0
1       0
2       0
3       0
4    0,05
Name: comision, dtype: object

## Método ffill()

In [48]:
#Este metodo se utiliza para rellenar los valores nulos con el valor anterior, 
#es decir, el valor que se encuentra en la fila anterior. En este caso, si hay 
# un valor nulo en la columna comision, se rellenará con el valor de la fila anterior.
#  Si el primer valor es nulo, no se rellenará y quedará como nulo.
df["comision"].ffill()

0        NaN
1        NaN
2        NaN
3        NaN
4       0,05
        ...
2995    0,09
2996    0,09
2997    0,09
2998    0,09
2999    0,09
Name: comision, Length: 3000, dtype: str

## Método bfill()

In [49]:
#Este metodo se utiliza para rellenar los valores hacia arriba  nulos con el valor siguiente, 
#es decir, el valor que se encuentra en la fila siguiente. En este caso, si

df["comision"].bfill()

# Hasta el momemto no se esta realizando la asiganacion, solo se esta mostrando el resultado. Para asignar el resultado a la columna comision, se debe hacer de la siguiente manera:
#df["comision"] = df["comision"].bfill()

0       0,05
1       0,05
2       0,05
3       0,05
4       0,05
        ...
2995    0,09
2996    0,09
2997    0,09
2998    0,09
2999    0,09
Name: comision, Length: 3000, dtype: str

## Eliminado columnas

In [50]:
# % de valores nulos por columna
df.isna().sum()/df.shape[0]*100
#Se observa que la columna comision tiene un 94,7% de valores nulos, por lo que se puede considerar eliminar esa columna o rellenar los valores nulos con algun valor

matricula_funcionario     0.0
nombre_funcionario        0.0
cargo                     0.0
codigo_tienda             0.0
nombre_tienda             0.0
codigo_producto           0.0
descripcion_producto      0.0
categoria                 0.0
precio_costo              0.0
valor_unitario            0.0
cantidad                  0.0
comision                 94.7
dt_venta                  0.0
dt_entrega                0.0
dtype: float64

In [51]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00

In [52]:
df.drop(columns=["comision"],inplace=True)

In [53]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,2019-08-14 16:56:00,2019-08-19 15:52:00

In [54]:
df.shape

(3000, 13)

#  <span style = "color: plum"> Creando Columnas Calculadas </span>

In [55]:
df.tail()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspiradora de piso,Casa,88.9,189.9,3,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Licuadora,Cocina,59.9,142.4,3,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batidora,Cocina,49.9,95.9,3,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Freidora eléctrica,Cocina,187.9,340.0,3,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,3,2019-03-18 15:40:00,2019-03-23 17:52:00

Recuerda las columnas son series

In [56]:
#Recueda ahi solo se esta mostrando el resultado, no se esta realizando la asiganacion a una nueva columna
df["valor_unitario"]*df["cantidad"]

0        404.1
1        249.9
2       1346.9
3       1676.9
4       1709.1
         ...
2995     569.7
2996     427.2
2997     287.7
2998    1020.0
2999    5127.3
Length: 3000, dtype: float64

## Guardando la nueva columna dentro del Date Frame

In [57]:
df["valor_total"]= df["valor_unitario"]*df["cantidad"]

In [58]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega,valor_total
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1

In [59]:
df.sample(10)

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega,valor_total
385,123456222,Maria das Gra√ßas,Vendedor,CL001,Tienda Matriz,10010,Freidora eléctrica,Cocina,187.9,340.0,4,2020-02-24 17:16:00,2020-02-25 14:53:00,1360.0
1616,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10001,Smartphone,Electrónicos,899.9,1676.9,4,2020-11-03 16:14:00,2020-11-03 17:31:00,6707.6
2295,123457112,Mario Enrique,Vendedor,CL004,Filial ES,10005,Notebook,Electrónicos,2299.9,3199.0,1,2019-11-09 13:57:00,2019-11-10 10:29:00,3199.0
1162,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10019,Sofá,Casa,789.9,1399.0,4,2019-06-23 15:45:00,2019-06-28 12:11:00,5596.0
2430,123457112,Mario Enrique,Vendedor,CL004,Filial ES,10005,Notebook,Electrónicos,2299.9,3199.0,2,2019-05-05 15:39:00,2019-05-06 13:05:00,6398.0
1910,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10020,Impresora,Electrónicos,329.9,674.1,3,2019-03-28 09:41:00,2019-03-29 09:28:00,2022.3
905,123456555,Marta Cury,Vendedor,CL002,Filial MG,10017,Cama Box,Casa,1189.9,1899.5,3,2019-09-28 11:53:00,2019-10-05 17:54:00,5698.5
2500,123457112,Mario Enrique,Vendedor,CL004,Filial ES,10006,Aspiradora de piso,Casa,88.9,189.9,3,2019-07-31 09:18:00,2019-07-31 16:06:00,569.7
2599,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10007,Batidora,Cocina,49.9,95.9,3,2020-07-20 15:17:00,2020-07-21 11:33:00,287.7
116,123456111,José María,Vendedor,CL001,Tienda Matriz,10020,Impresora,Electrónicos,329.9,674.1,3,2019-04-03 16:51:00,2019-04-04 12:03:00,2022.3

# <span style = "color: plum"> Ordenando Datos </span>

Se puede ordenar los datos por una o varias variables

In [60]:
datos = {"nombre_funcionario": ["Juan Perez","Ana Rodriguez", "Maria Gomez", "Ana Cachorro", "Carlos Sanchez"], 
         "edad" : [30, 25, 35, 28, 40],
         "pais": ["Argentina", "Chile", "Peru", "Bolivia", "Ecuador"]}
df_datos = pd.DataFrame(datos)
df_datos

  nombre_funcionario  edad       pais
0         Juan Perez    30  Argentina
1      Ana Rodriguez    25      Chile
2        Maria Gomez    35       Peru
3       Ana Cachorro    28    Bolivia
4     Carlos Sanchez    40    Ecuador

In [61]:
# Ordenadndo por nombe
df_datos.sort_values("nombre_funcionario", ascending=True)

  nombre_funcionario  edad       pais
3       Ana Cachorro    28    Bolivia
1      Ana Rodriguez    25      Chile
4     Carlos Sanchez    40    Ecuador
0         Juan Perez    30  Argentina
2        Maria Gomez    35       Peru

In [62]:
#Organizando por dos variables
df_datos.sort_values(["nombre_funcionario", "edad"], ascending=[True, False])

  nombre_funcionario  edad       pais
3       Ana Cachorro    28    Bolivia
1      Ana Rodriguez    25      Chile
4     Carlos Sanchez    40    Ecuador
0         Juan Perez    30  Argentina
2        Maria Gomez    35       Peru

In [63]:
df.sort_values("nombre_funcionario", ascending=True, inplace=True)

In [64]:
df.head()
#Observa que los indices quedaron en desorden, si quieres ordenarlos, puedes hacer lo siguiente:

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega,valor_total
1757,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,3,2020-08-25 10:04:00,2020-08-31 16:39:00,1212.3
1710,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10011,Licuadora,Cocina,59.9,142.4,2,2020-06-10 15:34:00,2020-06-11 13:59:00,284.8
1711,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,2,2019-03-21 15:58:00,2019-03-28 09:44:00,808.2
1712,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,2,2019-09-16 14:46:00,2019-09-20 09:22:00,3418.2
1713,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10005,Notebook,Electrónicos,2299.9,3199.0,2,2019-11-25 16:28:00,2019-11-26 13:42:00,6398.0

# <span style ="color: plum" > Restaurando Reset el índice </span>

In [65]:
df.reset_index()

,index,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega,valor_total
0,1757,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,3,2020-08-25 10:04:00,2020-08-31 16:39:00,1212.3
1,1710,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10011,Licuadora,Cocina,59.9,142.4,2,2020-06-10 15:34:00,2020-06-11 13:59:00,284.8
2,1711,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,2,2019-03-21 15:58:00,2019-03-28 09:44:00,808.2
3,1712,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,2,2019-09-16 14:46:00,2019-09-20 09:22:00,3418.2
4,1713,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10005,Notebook,Electrónicos,2299.9,3199.0,2,2019-11-25 16:28:00,2019-11-26 13:42:00,6398.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2834,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10017,Cama Box,Casa,1189.9,1899.5,4,2019-04-17 15:36:00,2019-04-24 15:55:00,7598.0
2996,2835,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10018,Colchón,Casa,109.9,249.9,2,2020-01-21 15:46:00,2020-01-21 16:20:00,499.8
2997,2836,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10012,Procesador de alimentos,Cocina,110.0,189.9,2,2020-10-22 17:06:00,2020-10-23 11:05:00,379.8
2998,2870,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10013,Fogón,Electrodomésticos,210.9,404.1,1,2019-02-18 16:04:00,2019-02-25 14:14:00,404.1
2999,2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,3,2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3

In [66]:
#Ordenar los indices y con el comando drop creo un nuevo indice, si no se pone drop=True, se crea una nueva columna con el indice anterior
df.reset_index(drop=True, inplace=True)

  # <span style = "Color: plum" > Modificando el índice </span >

In [67]:
df.set_index("dt_venta", inplace=True)

In [68]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_entrega,valor_total
dt_venta,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
2020-06-10 15:34:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10011,Licuadora,Cocina,59.9,142.4,2,2020-06-11 13:59:00,284.8
2019-03-21 15:58:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
2019-09-16 14:46:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
2019-11-25 16:28:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10005,Notebook,Electrónicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0

In [69]:
df.index

DatetimeIndex(['2020-08-25 10:04:00', '2020-06-10 15:34:00',
               '2019-03-21 15:58:00', '2019-09-16 14:46:00',
               '2019-11-25 16:28:00', '2019-09-28 12:02:00',
               '2019-11-01 11:05:00', '2020-11-01 11:48:00',
               '2020-06-23 10:47:00', '2020-04-01 16:50:00',
               ...
               '2020-02-13 13:54:00', '2019-02-09 09:49:00',
               '2020-11-02 09:04:00', '2020-04-08 16:03:00',
               '2020-01-29 13:19:00', '2019-04-17 15:36:00',
               '2020-01-21 15:46:00', '2020-10-22 17:06:00',
               '2019-02-18 16:04:00', '2019-03-18 15:40:00'],
              dtype='datetime64[us]', name='dt_venta', length=3000, freq=None)

# <span style= "color : plum"> Accediendo con un indice de fecha </span>

In [70]:
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_entrega,valor_total
dt_venta,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
2020-06-10 15:34:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10011,Licuadora,Cocina,59.9,142.4,2,2020-06-11 13:59:00,284.8
2019-03-21 15:58:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
2019-09-16 14:46:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
2019-11-25 16:28:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10005,Notebook,Electrónicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0

In [71]:
df.loc["2020-04"].head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_entrega,valor_total
dt_venta,,,,,,,,,,,,,
2020-04-01 16:50:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10010,Freidora eléctrica,Cocina,187.9,340.00,2,2020-04-02 15:20:00,680.00
2020-04-26 16:36:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10020,Impresora,Electrónicos,329.9,674.10,3,2020-04-27 11:27:00,2022.30
2020-04-07 13:32:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10018,Colchón,Casa,109.9,249.90,3,2020-04-07 14:37:00,749.70
2020-04-17 12:28:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10003,Televisor,Electrodomésticos,1400.9,2279.99,3,2020-04-23 13:59:00,6839.97
2020-04-19 10:22:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10001,Smartphone,Electrónicos,899.9,1676.90,3,2020-04-19 17:16:00,5030.70

# <span style  = "Color : plum">  Exportandp un DataFrame </span>

In [72]:
df.to_csv("datasets/base_ventas_tratada.csv"
)

In [74]:
# Si quiero exportar el dataframe sin los indices, puedo hacer lo siguiente:
df_Original.to_csv("datasets/base_ventas_Original_sin_indices.csv", index=False)

In [75]:
df_base_exportada = pd.read_csv("datasets/base_ventas_tratada.csv")

In [76]:
# Quiero leer el archivo y quiero decirle cual es el indice que quiero para el DataFrame
df_base_exportada = pd.read_csv("datasets/base_ventas_tratada.csv", index_col="dt_venta")

In [77]:
df_base_exportada.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_entrega,valor_total
dt_venta,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
2020-06-10 15:34:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10011,Licuadora,Cocina,59.9,142.4,2,2020-06-11 13:59:00,284.8
2019-03-21 15:58:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10013,Fogón,Electrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
2019-09-16 14:46:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
2019-11-25 16:28:00,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10005,Notebook,Electrónicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0